apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-beta-fullnode2
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    chart: pocketd
    repoURL: https://pokt-network.github.io/helm-charts
    targetRevision: 0.1.1
    helm:
      values: |
        # Can be created with `kubectl create secret generic fullnode2-keys --from-file=config/node_key.json --from-file=config/priv_validator_key.json --namespace=testnet-beta`
        nodeKeysSecretName: fullnode2-keys

        podLabels:
          fullnodes-service-include: "true"

        # Can be created with `kubectl create cm testnet-test-genesis --from-file=config/genesis.json --namespace=testnet-beta`
        # Provisioned below
        genesis:
          configMapName: genesis

        replicaCount: 1

        image:
          repository: ghcr.io/pokt-network/pocketd
          tag: 0.1.1 # Don't change. Cosmovisor handles versioning.
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          className: "vultr-block-storage"
          size: 200Gi

        cosmovisor:
          enabled: true

        resources:
          limits:
            memory: 12Gi
            cpu: '4'
          requests:
            memory: 12Gi
            cpu: '2'

        serviceP2P:
          type: LoadBalancer
          externalTrafficPolicy: Local

        config:
          p2p:
            externalAddress: "149.28.51.149:26656"
            seeds: 78e64eb51f040b86b8e4bed6ba8d895fa2f87839@shannon-grove-seed1.beta.poktroll.com:26656

        serviceMonitor:
          enabled: true

        logs:
          format: json
          level: error

        homeDirectory: /home/pocket/.pocket
        chownDataDirTo: 1025
        containerSecurityContext:
          runAsUser: 1025
          runAsGroup: 1025

        customConfigsConfigMap:
          enabled: true
          name: custom-configs
