# Secret created with: kubectl create secret generic --context=vke-9c40c45d-3958-46fd-8b11-3f53643ba73e --namespace=testnet-beta --from-file=./keyring-test/beta-prod-relayminer-1.info --from-file=./keyring-test/beta-prod-relayminer-2.info prod-relayminers
---
# Staked manually with the following command:
# cat <<EOF >stake_config.yaml
# stake_amount: 1000001upokt
# owner_address: pokt186qnzaum86cx5e7dh2fm6t5me8f29n93p7ap33
# services:
# - service_id: pocket-beta-rpc
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-1.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# - service_id: pocket-beta-api
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-1.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# - service_id: pocket-beta-grpc
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-1.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# EOF
# pkd_beta_tx tx supplier stake-supplier --config=stake_config.yaml --from=beta-prod-relayminer-1 --yes

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-relayminer-1
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "testnet-beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: main # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        replicaCount: 1
        logs:
          level: info # others are info
        chainId: pocket-beta
        keysSecretName: prod-relayminers
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 2Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        image:
          tag: 0.0.12
        homeDirectory: /home/pocket/.poktroll
        chownDataDirTo: 1025
        podSecurityContext:
          fsGroup: 1025
          runAsUser: 1025
          runAsGroup: 1025

        securityContext:
          runAsNonRoot: true
          runAsUser: 1025
          allowPrivilegeEscalation: false
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: prod-relayminer-1.us-nj.poktroll.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: poktroll-wildcard-tls
              hosts:
                - prod-relayminer-1.us-nj.poktroll.com
        grpcInsecure: true
        config:
          signing_key_name: beta-prod-relayminer-1 # For backwards compatibility with chart
          default_signing_key_names: [beta-prod-relayminer-1]
          smt_store_path: /home/pocket/.poktroll
          pocket_node:
            query_node_rpc_url: tcp://testnet-beta-fullnodes:26657
            query_node_grpc_url: tcp://testnet-beta-fullnodes:9090
            tx_node_rpc_url: tcp://testnet-beta-fullnodes:26657
          suppliers:
            - service_id: pocket-beta-rpc
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:26657
                publicly_exposed_endpoints:
                  - prod-relayminer-1.us-nj.poktroll.com
            - service_id: pocket-beta-api
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:1317
                publicly_exposed_endpoints:
                  - prod-relayminer-1.us-nj.poktroll.com
            - service_id: pocket-beta-grpc
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:9090
                publicly_exposed_endpoints:
                  - prod-relayminer-1.us-nj.poktroll.com
---
# Staked manually with the following command:
# cat <<EOF >stake_config.yaml
# stake_amount: 1000001upokt
# owner_address: pokt1z0w03mr6x2lfn9vurrezxx9n36fg5rglakkkwm
# services:
# - service_id: pocket-beta-rpc
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-2.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# - service_id: pocket-beta-api
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-2.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# - service_id: pocket-beta-grpc
#   endpoints:
#   - publicly_exposed_url: https://prod-relayminer-2.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# EOF
# pkd_beta_tx tx supplier stake-supplier --config=stake_config.yaml --from=beta-prod-relayminer-2 --yes

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-relayminer-2
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "testnet-beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: main # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        replicaCount: 1
        logs:
          level: info # others are info
        chainId: pocket-beta
        keysSecretName: prod-relayminers
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 2Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        image:
          tag: 0.0.12
        homeDirectory: /home/pocket/.poktroll
        chownDataDirTo: 1025
        podSecurityContext:
          fsGroup: 1025
          runAsUser: 1025
          runAsGroup: 1025

        securityContext:
          runAsNonRoot: true
          runAsUser: 1025
          allowPrivilegeEscalation: false
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: prod-relayminer-2.us-nj.poktroll.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: poktroll-wildcard-tls
              hosts:
                - prod-relayminer-2.us-nj.poktroll.com
        grpcInsecure: true
        config:
          signing_key_name: beta-prod-relayminer-2 # For backwards compatibility with chart
          default_signing_key_names: [beta-prod-relayminer-2]
          smt_store_path: /home/pocket/.poktroll
          pocket_node:
            query_node_rpc_url: tcp://testnet-beta-fullnodes:26657
            query_node_grpc_url: tcp://testnet-beta-fullnodes:9090
            tx_node_rpc_url: tcp://testnet-beta-fullnodes:26657
          suppliers:
            - service_id: pocket-beta-rpc
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:26657
                publicly_exposed_endpoints:
                  - prod-relayminer-2.us-nj.poktroll.com
            - service_id: pocket-beta-api
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:1317
                publicly_exposed_endpoints:
                  - prod-relayminer-2.us-nj.poktroll.com
            - service_id: pocket-beta-grpc
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://testnet-beta-fullnodes:9090
                publicly_exposed_endpoints:
                  - prod-relayminer-2.us-nj.poktroll.com
---

