apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-beta-seed1
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    chart: pocketd
    repoURL: https://pokt-network.github.io/helm-charts
    targetRevision: 0.1.1
    helm:
      values: |
        # Can be created with `kubectl create secret generic seed1-keys --from-file=config/node_key.json --from-file=config/priv_validator_key.json --namespace=testnet-beta`
        nodeKeysSecretName: seed1-keys

        podLabels:
          fullnodes-service-include: "true"

        # Can be created with `kubectl create cm testnet-test-genesis --from-file=config/genesis.json --namespace=testnet-beta`
        # Provisioned below
        genesis:
          configMapName: genesis

        replicaCount: 1

        image:
          repository: ghcr.io/pokt-network/pocketd
          tag: 0.1.1 # Don't change. Cosmovisor handles versioning.
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          className: "vultr-block-storage"
          size: 150Gi

        cosmovisor:
          enabled: true

        resources:
          limits:
            memory: 16Gi
            cpu: '6'
          requests:
            memory: 15Gi
            cpu: '4'

        serviceP2P:
          type: LoadBalancer
          externalTrafficPolicy: Local

        config:
          p2p:
            seedMode: true
            externalAddress: "45.77.207.136:26656"
            persistentPeers: "886651a13de02c737804097ef19f426f6be37d71@45.77.220.185:26656"
            unconditionalPeerIds: "886651a13de02c737804097ef19f426f6be37d71"

        serviceMonitor:
          enabled: true

        logs:
          format: json
          level: error

        homeDirectory: /home/pocket/.pocket
        chownDataDirTo: 1025
        containerSecurityContext:
          runAsUser: 1025
          runAsGroup: 1025

        customConfigsConfigMap:
          enabled: true
          name: custom-configs
