apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-beta-validator2
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    chart: pocketd
    repoURL: https://pokt-network.github.io/helm-charts
    targetRevision: 0.1.1
    helm:
      values: |
        # Can be created with `kubectl create secret generic validator2-keys --from-file=config/node_key.json --from-file=config/priv_validator_key.json --namespace=testnet-beta`
        nodeKeysSecretName: validator2-keys

        # Can be created with `kubectl create cm testnet-test-genesis --from-file=config/genesis.json --namespace=testnet-beta`
        # Provisioned below
        genesis:
          configMapName: genesis

        replicaCount: 1

        image:
          repository: ghcr.io/pokt-network/pocketd
          tag: 0.1.1 # Don't change. Cosmovisor handles versioning.
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          className: "vultr-block-storage"
          size: 150Gi

        cosmovisor:
          enabled: true

        resources:
          limits:
            memory: 16Gi
            cpu: '6'
          requests:
            memory: 15Gi
            cpu: '4'

        serviceP2P:
          type: LoadBalancer
          externalTrafficPolicy: Local

        config:
          p2p:
            externalAddress: "45.63.1.164:26656"
            seeds: 78e64eb51f040b86b8e4bed6ba8d895fa2f87839@shannon-grove-seed1.beta.poktroll.com:26656

        serviceMonitor:
          enabled: true
          interval: 5s

        logs:
          format: json
          level: error

        # ingress:
        #   rpc:
        #     enabled: true
        #     annotations:
        #       kubernetes.io/ingress.class: nginx
        #     hosts:
        #       - name: shannon-testnet-grove-val1-rpc.beta.poktroll.com
        #     tls:
        #       secretName: "beta-wildcard-tls"
        #   grpc:
        #     enabled: true
        #     annotations:
        #       kubernetes.io/ingress.class: nginx
        #       nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        #     hosts:
        #       - name: shannon-testnet-grove-val1-grpc.beta.poktroll.com
        #     tls:
        #       secretName: "beta-wildcard-tls"
        #   api:
        #     enabled: true
        #     annotations:
        #       kubernetes.io/ingress.class: nginx
        #     hosts:
        #       - name: shannon-testnet-grove-val1-api.beta.poktroll.com
        #     tls:
        #       secretName: "beta-wildcard-tls"

        homeDirectory: /home/pocket/.pocket
        chownDataDirTo: 1025
        containerSecurityContext:
          runAsUser: 1025
          runAsGroup: 1025

        customConfigsConfigMap:
          enabled: true
          name: custom-configs
