---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-data-rwx
  namespace: protocol-common
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: "vultr-block-storage" # Use HDD storage for lower cost
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-vfs-storage
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  storage_type: "vfs"
  disk_type: "nvme"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-vfs-storage-retain
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storage_type: "vfs"
  disk_type: "nvme"