# protocol-nj
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: protocol-infra-protocol-nj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: clusters/protocol-nj
    repoURL: https://github.com/pokt-network/protocol-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    - /spec/storageClassName
    kind: PersistentVolumeClaim
