---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-validator
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "public-testnet"
    provisioned-by: "protocol"
spec:
  project: default
  source:
    path: charts/poktrolld
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: dk-poktrolld-full-node # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        nodeKeysSecretName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}
        genesis:
          configMapName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}

        replicaCount: 1

        image:
          tag: {{ .Values.image.tag }}

        persistence:
          enabled: true
          className: "premium-rwo"
          size: 10Gi

        resources:
          limits:
            memory: 1Gi
            cpu: 2
          requests:
            memory: 1Gi
            cpu: 0.5

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - name: {{ .Values.network.type }}-{{ .Values.network.name }}-seqeuncer-rpc.poktroll.com
          tls:
            secretName: "poktroll-wildcard-tls"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  ignoreDifferences:
  - jsonPointers:
    - /spec/VolumeName
    - /spec/StorageClassName
    kind: PersistentVolumeClaim
  destination:
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
    server: https://kubernetes.default.svc