apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
  project: default
  source:
    path: charts/poktroll-sequencer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: add-resources
    # targetRevision: {{ .Values.charts.sequencer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
        image:
          tag: {{ .Values.image.tag }}
        configsConfigMapName: configs-{{ .Values.image.tag }}
        keysConfigMapName: keys-{{ .Values.image.tag }}
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 0.5
            memory: 2Gi
        dataAvailability:
          provider: celestia
          authToken:
            secretName: celestia-secret
            secretKey: auth_token
          celestia:
            hostname: celestia-rollkit.protocol-common.svc.cluster.local
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  ignoreDifferences:
  - jsonPointers:
    - /spec/VolumeName
    - /spec/StorageClassName
    kind: PersistentVolumeClaim
