# Deployes an instance of 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
  project: default
  source:
    path: charts/poktroll-sequencer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: {{ .Values.charts.sequencer.branch }}
    helm: 
      values: |
        image:
          repository: ghcr.io/pokt-network/pocketd
          tag: sha-6ac7cf1
          pullPolicy: IfNotPresent
        dataAvailability:
          provider: celestia
          authToken:
            secretName: celestia-secret
            secretKey: auth_token
          celestia:
            hostname: celestia-rollkit.protocol-common.svc.cluster.local
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true