apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-relayminer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
  project: default
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: {{ .Values.charts.sequencer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ .Values.network.type }}-{{ .Values.network.name }}-relayminer
        configsConfigMapName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}
        keysConfigMapName: {{ default (printf "keys-%s" .Values.image.tag) .Values.customConfigMap.keysName }}
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 0.25
            memory: 512Mi
        image:
          tag: {{ .Values.image.tag }}
        config:
          # \/ Keep for backwards compatibility
          query_node_url: tcp://{{ .Values.network.type }}-{{ .Values.network.name }}-sequencer:36657
          network_node_url: tcp://{{ .Values.network.type }}-{{ .Values.network.name }}-sequencer:36657
          # ^ Keep for backwards compatibility

          pocket_node:
            query_node_rpc_url: tcp://{{ .Values.network.type }}-{{ .Values.network.name }}-sequencer:36657
            query_node_grpc_url: tcp://{{ .Values.network.type }}-{{ .Values.network.name }}-sequencer:36658
            tx_node_grpc_url: tcp://{{ .Values.network.type }}-{{ .Values.network.name }}-sequencer:36658

          proxies:
            - proxy_name: http-proxy
              type: http
              host: 0.0.0.0:8545
          suppliers:
            - service_id: anvil
              type: http
              service_config:
                url: http://anvil:8547/
              proxy_names:
                - http-proxy
              hosts:
                - tcp://relayminers:8545

  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  # ignoreDifferences:
  # - jsonPointers:
  #   - /spec/VolumeName
  #   - /spec/StorageClassName
  #   kind: PersistentVolumeClaim
