apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-appgate-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
  project: default
  source:
    path: charts/appgate-server
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: {{ .Values.charts.sequencer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ .Values.network.type }}-{{ .Values.network.name }}-appgate-server
        configsConfigMapName: configs-{{ .Values.image.tag }}
        keysConfigMapName: keys-{{ .Values.image.tag }}
        image:
          tag: {{ .Values.image.tag }}
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  # ignoreDifferences:
  # - jsonPointers:
  #   - /spec/VolumeName
  #   - /spec/StorageClassName
  #   kind: PersistentVolumeClaim
