apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
  project: default
  source:
    path: charts/poktroll-sequencer
    repoURL: https://github.com/pokt-network/helm-charts.git
    # targetRevision: add-resources
    targetRevision: {{ .Values.charts.sequencer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
        image:
          tag: {{ .Values.image.tag }}
        configsConfigMapName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}
        keysConfigMapName: {{ default (printf "keys-%s" .Values.image.tag) .Values.customConfigMap.keysName }}
        {{ toYaml .Values.sequencer | nindent 8 }}

        # for troubleshooting: {{.}}
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  ignoreDifferences:
  - jsonPointers:
    - /spec/VolumeName
    - /spec/StorageClassName
    kind: PersistentVolumeClaim
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.network.type }}-{{ .Values.network.name }}-sequencer
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "public-testnet"
    provisioned-by: "protocol"
spec:
  project: default
  source:
    path: charts/poktrolld
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: dk-poktrolld-full-node # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        celestia-da:
          enabled: false

        nodeKeysSecretName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}

        genesis:
          configMapName: {{ default (printf "configs-%s" .Values.image.tag) .Values.customConfigMap.configsName }}

        replicaCount: 1

        image:
          tag: {{ .Values.image.tag }}

        persistence:
          enabled: true
          className: "premium-rwo"
          size: 10Gi

        resources:
          limits:
            memory: 1Gi
            cpu: 2
          requests:
            memory: 1Gi
            cpu: 0.5

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - name: {{ .Values.network.type }}-{{ .Values.network.name }}-seqeuncer-rpc.poktroll.com
          tls:
            secretName: "poktroll-wildcard-tls"

        rollkit:
          aggregator: true
          block_time: 60s
          da_address: "celestia-rollkit.protocol-common.svc.cluster.local:26658"
          da_namespace: '00000000000000000000000000000000000000000034cbeef696969420'
          da_block_time: 15s
          da_gas_price: 0.01
          # da_gas_multiplier: 1.2
          da_start_height: 1 # Latest block on when the rollup starts.

  destination:
    namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
    server: https://kubernetes.default.svc