apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
spec:
  type: ExternalName
  externalName: anvil.protocol-common.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: relayminers
  namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
spec:
  selector:
    app.kubernetes.io/name: relayminer # TODO(@okdas): use pokt.network/purpose when its ready
  ports:
  - name: http
    port: 8545
    protocol: TCP
    targetPort: 8545