apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
spec:
  type: ExternalName
  externalName: anvil.protocol-common.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: relayminers
  namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
spec:
  selector:
    pokt.network/purpose: relayminer
  ports:
  - name: http
    port: 8545
    protocol: TCP
    targetPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: sequencer-poktroll-sequencer
  namespace: {{ .Values.network.type }}-{{ .Values.network.name }}
spec:
  selector:
    pokt.network/purpose: sequencer
  ports:
  - name: http
    port: 36657
    protocol: TCP
    targetPort: 36657