---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
  namespace: protocol-common
  labels:
    provisioned-by: "protocol"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
        provisioned-by: "protocol"
    spec:
      resources:
        limits:
          cpu: "1" 
          memory: "1Gi"
        requests:
          cpu: "0.2"
          memory: "512Mi"      
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:latest
          ports:
            - containerPort: 8545
          command: ["anvil"]
          args: ["-p", "8545", "-b", "5", "--host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: protocol-common
  labels:
    provisioned-by: "protocol"
spec:
  selector:
    app: anvil
  ports:
    - protocol: TCP
      name: rpc
      port: 8545
      targetPort: 8545
