apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirrors-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kts.studio
    chart: mirrors
    targetRevision: 0.1.8
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Namespace where you want to install the chart
  syncPolicy:
    automated: # Enables automated sync
      prune: true # Enables pruning of resources not tracked anymore
      selfHeal: true # Enables self-healing of out-of-sync resources
