apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirrors-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kts.studio
    chart: mirrors
    targetRevision: 0.1.8
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: # Enables automated sync
      prune: true # Enables pruning of resources not tracked anymore
      selfHeal: false # Enables self-healing of out-of-sync resources
  ignoreDifferences:
  - group: cert-manager.io
    kind: Certificate
    jsonPointers:
    - /spec/duration
    - /spec/renewBefore