apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # https://argoproj.github.io/argo-cd/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.8.3
    # helm:
    #   values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
