apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # https://argoproj.github.io/argo-cd/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |
        controller:
          replicaCount: 2
          service:
            externalTrafficPolicy: Local
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
