apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-vm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.18.6
    helm:
      values: |
        fullnameOverride: vm
        argocdReleaseOverride: observability-vm
        vmsingle:
          spec:
            retentionPeriod: "1"
            storage:
              resources:
                requests:
                  storage: 20Gi
              storageClassName: pd-standard
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: # Enables automated sync
      prune: false # Enables pruning of resources not tracked anymore
      selfHeal: false # Enables self-healing of out-of-sync resources
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
---

