apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-vm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.18.6
    helm:
      values: |
        fullnameOverride: vm
        argocdReleaseOverride: observability-vm
        vmsingle:
          spec:
            retentionPeriod: "1"
            storage:
              resources:
                requests:
                  storage: 20Gi
              storageClassName: standard

        vmagent:
          spec:
            selectAllByDefault: true # all namespaces
            externalLabels:
              cluster: protocol-us-central1
              cloud_provider: gcp
              region: us-central1
              team: protocol

        vmalert:
          spec:
            externalLabels:
              cluster: protocol-us-central1
              cloud_provider: gcp
              region: us-central1
              team: protocol

        # TODO: set `GF_AUTH_GITHUB_CLIENT_ID`, `GF_AUTH_GITHUB_CLIENT_SECRET`, via extra env mounts
        # TODO: add certificate
        grafana:
          adminPassword: initialPassword
          grafana.ini:
            server:
              domain: grafana.protocol.pokt.network
              root_url: https://grafana.protocol.pokt.network
            # auth.github:
            #   enabled: true
            #   allow_sign_up: true
            #   scopes: user:email,read:org
            #   auth_url: https://github.com/login/oauth/authorize
            #   token_url: https://github.com/login/oauth/access_token
            #   api_url: https://api.github.com/user
            #   allowed_organizations: pokt-foundation pokt-network
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - grafana.protocol.pokt.network
            tls:
              - secretName: grafana-srvio-tls
                hosts:
                - grafana.protocol.pokt.network
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - Replace=true
    automated: # Enables automated sync
      prune: false # Enables pruning of resources not tracked anymore
      selfHeal: false # Enables self-healing of out-of-sync resources
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
---

