{
 "title": "V1 Network Validators",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network name",
    "query": {
     "query": "label_values(consensus_blockchain_height_counter, namespace)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(consensus_blockchain_height_counter, region)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height destribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(pod) (consensus_blockchain_height_counter{region=\"$region\", namespace=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockchain height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consensus_blockchain_height_counter{region=\"$region\", namespace=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(consensus_blockchain_height_counter{region=\"$region\", namespace=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(validator) (label_replace(node_namespace_pod_container:container_memory_working_set_bytes{region=\"$region\", namespace=\"$network\", container=\"pocket-validator\"}, \"validator\", \"$1\", \"pod\", \".*-(validator.*)-.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "description": "CPU usage seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(validator) (label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{region=\"$region\", namespace=\"$network\", container=\"pocket-validator\"}, \"validator\", \"$1\", \"pod\", \".*-(validator.*)-.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go process metrics (routines, heap, etc.)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Validators logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"pocket-validator\", namespace=\"$network\"} |= ``",
     "maxLines": 500
    }
   ]
  }
 ]
}