apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testnet-beta-validator1
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: testnet-beta
    server: https://kubernetes.default.svc
  source:
    path: charts/poktrolld
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: adopt-prod-image # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        # Can be created with `kubectl create secret generic validator1-keys --from-file=config/node_key.json --from-file=config/priv_validator_key.json --namespace=testnet-beta`
        nodeKeysSecretName: validator1-keys

        # Can be created with `kubectl create cm testnet-test-genesis --from-file=config/genesis.json --namespace=testnet-beta`
        # Provisioned below
        genesis:
          configMapName: testnet-validated-genesis

        replicaCount: 1

        image:
          repository: ghcr.io/pokt-network/poktrolld
          tag: 0.0.11-rc
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          className: "premium-rwo"
          size: 80Gi

        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 1.5

        serviceP2P:
          type: LoadBalancer
          externalTrafficPolicy: Local
          annotations:
            cloud.google.com/neg: '{"ingress":true}'

        config:
          p2p:
            externalAddress: ""

        serviceMonitor:
          enabled: true

        ingress:
          rpc:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - name: shannon-testnet-beta-grove-validator1-rpc.poktroll.com
            tls:
              secretName: "poktroll-wildcard-tls"
          grpc:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
            hosts:
              - name: shannon-testnet-beta-grove-validator1-grpc.poktroll.com
            tls:
              secretName: "poktroll-wildcard-tls"
          api:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - name: shannon-testnet-beta-grove-validator1-api.poktroll.com
            tls:
              secretName: "poktroll-wildcard-tls"

        customConfigsConfigMap:
          enabled: true
          name: custom-configs
