apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: dev-e2e-tests-
spec:
  serviceAccountName: e2e-tests
  entrypoint: test-e2e
  arguments:
    parameters:
      - name: gitsha

  templates:
    - name: test-e2e
      inputs:
        parameters:
        - name: gitsha
      container:
        image: "ghcr.io/pokt-network/pocket-v1:sha-{{ "{{" }}inputs.parameters.gitsha{{ "}}" }}-dev"
        imagePullPolicy: IfNotPresent
        command: [make, test_e2e]
        env:
          - name: RPC_HOST
            value: pocket-validators
        resources:
          limits:
            cpu: "4"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
