apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-tests
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-tests
subjects:
  - kind: ServiceAccount
    name: e2e-tests
    apiGroup: ""
roleRef:
  kind: Role
  name: e2e-tests
  apiGroup: ""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-tests
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["validators-private-keys"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch"]
