{{- $networkType := .Values.network.type }}
{{- $networkName := .Values.network.name }}
{{- $imageTag := .Values.image.tag }}
{{- $relayMinerCount := default 1 .Values.relayminers.count | int }}

{{- range $i := until $relayMinerCount }}
{{- $relayMinerNumber := add $i 1 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $networkType }}-{{ $networkName }}
  project: default
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: main # TODO: change to versioned releases when the work on the helm chart is merged/done # {{ $.Values.charts.relayminer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}
        configsConfigMapName: {{ default (printf "configs-%s" $imageTag) $.Values.customConfigMap.configsName }}
        keysSecretName: {{ default (printf "keys-%s" $imageTag) $.Values.customConfigMap.keysName }}
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.25
            memory: 512Mi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        image:
          tag: {{ $imageTag }}
        config:
          default_signing_key_names: [supplier{{ $relayMinerNumber }}]
          pprof:
            enabled: true
          pocket_node:
            query_node_rpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
            query_node_grpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:9090
            tx_node_rpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
          suppliers:
            - service_id: ollama
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://ollama:11434/
                publicly_exposed_endpoints:
                  - relayminer{{ $relayMinerNumber }} # schema and port intentionally omitted 
            - service_id: anvil
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: http://anvil:8547/
                publicly_exposed_endpoints:
                  - relayminer{{ $relayMinerNumber }} # schema and port intentionally omitted 

  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  # ignoreDifferences:
  # - jsonPointers:
  #   - /spec/VolumeName
  #   - /spec/StorageClassName
  #   kind: PersistentVolumeClaim
{{- end }}
