{{- $networkType := .Values.network.type }}
{{- $networkName := .Values.network.name }}
{{- $imageTag := .Values.image.tag }}
{{- $relayMinerCount := default 1 .Values.relayminers.count | int }}

{{- range $i := until $relayMinerCount }}
{{- $relayMinerNumber := add $i 1 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $networkType }}-{{ $networkName }}
  project: default
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: main # TODO: change to versioned releases when the work on the helm chart is merged/done # {{ $.Values.charts.relayminer.branch }}
    helm: 
      values: |
        fullnameOverride: {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}
        configsConfigMapName: {{ default (printf "configs-%s" (default $imageTag $.Values.configVersion)) $.Values.customConfigMap.configsName }}
        keysSecretName: {{ default (printf "keys-%s" (default $imageTag $.Values.configVersion)) $.Values.customConfigMap.keysName }}
        resources:
          {{- toYaml (default $.Values.relayminers.resources dict) | nindent 10 }}
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        image:
          tag: {{ $imageTag }}
        grpcInsecure: true
        config:
          default_signing_key_names: [supplier{{ $relayMinerNumber }}]
          pprof:
            enabled: true
          pocket_node:
            query_node_rpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
            query_node_grpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:9090
            tx_node_rpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
          suppliers:
            - service_id: anvil
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: {{ default "http://anvil:8547/" $.Values.relayminers.services.anvil.backend_url }}
                publicly_exposed_endpoints:
                  - relayminer{{ $relayMinerNumber }}
                  - {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}.poktroll.com
            - service_id: anvilws
              listen_url: http://0.0.0.0:8545
              service_config:
                backend_url: {{ default "ws://anvil:8547/" $.Values.relayminers.services.anvilws.backend_url }}
                publicly_exposed_endpoints:
                  - relayminer{{ $relayMinerNumber }}
                  - {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}.poktroll.com
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}.poktroll.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: poktroll-wildcard-tls
              hosts:
                - {{ $networkType }}-{{ $networkName }}-relayminer-{{ $relayMinerNumber }}.poktroll.com
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  # ignoreDifferences:
  # - jsonPointers:
  #   - /spec/VolumeName
  #   - /spec/StorageClassName
  #   kind: PersistentVolumeClaim
{{- end }}
