{{- $networkType := .Values.network.type }}
{{- $networkName := .Values.network.name }}
{{- $imageTag := .Values.image.tag }}
{{- $gatewayCount := default 1 .Values.gateways.count | int }}

{{- range $i := until $gatewayCount }}
{{- $gatewayNumber := add $i 1 }}
{{- $nameSuffix := ternary "" (printf "-%d" $gatewayNumber) (eq $gatewayCount 1) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $networkType }}-{{ $networkName }}-gateway{{ $nameSuffix }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $networkType }}-{{ $networkName }}
  project: default
  source:
    path: charts/appgate-server
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: main
    helm: 
      values: |
        fullnameOverride: {{ $networkType }}-{{ $networkName }}-gateway{{ $nameSuffix }}
        configsConfigMapName: {{ default (printf "configs-%s" $imageTag) $.Values.customConfigMap.configsName }}
        keysSecretName: {{ default (printf "keys-%s" $imageTag) $.Values.customConfigMap.keysName }}
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.25
            memory: 512Mi
        service:
          port: 80
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        config:
          self_signing: false
          signing_key: gateway{{ $gatewayNumber }}
          query_node_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
          listening_endpoint: http://0.0.0.0:80
          query_node_rpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:26657
          query_node_grpc_url: tcp://{{ $networkType }}-{{ $networkName }}-validator-poktrolld:9090
          pprof:
            enabled: true
        image:
          tag: {{ $imageTag }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: {{ $networkType }}-{{ $networkName }}-gateway{{ $nameSuffix }}.poktroll.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: poktroll-wildcard-tls
              hosts:
                - {{ $networkType }}-{{ $networkName }}-gateway{{ $nameSuffix }}.poktroll.com
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
{{- end }}
