# We need postgres operator to provision databases for Validators
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    provisioned-by: "protocol"
spec:
  destination:
    name: dev-in-cluster
    namespace: actions-runner-system
  project: default
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.23.3
    helm: {}
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
# ---
# apiVersion: actions.summerwind.dev/v1alpha1
# kind: RunnerDeployment
# metadata:
#   name: pokt-network-runner
#   namespace: actions-runner-system
# spec:
#   replicas: 2
#   template:
#     spec:
#       organization: pokt-network
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: pokt-network-pocket
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: pokt-network/pocket
      labels:
        - custom-runner
      resources:
        limits:
          cpu: "16.0"
          memory: "16Gi"
        requests:
          cpu: "2.0"
          memory: "8Gi"
      dockerdContainerResources:
        limits:
          cpu: "16.0"
          memory: "16Gi"
        requests:
          cpu: "2.0"
          memory: "8Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: pokt-network-pocket
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: pokt-network-pocket
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - pocket
