apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-pocket-operator
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "pocket-operator"
    provisioned-by: "protocol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: dev-in-cluster
    namespace: pocket-operator
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/pokt-network/pocket-operator.git
    path: config/default
    targetRevision: master # TODO(@okdas): Change this to a tag when we have versions
    kustomize:
      # Supported kustomize transformers. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
      commonLabels:
        purpose: pocket-operator
        team: protocol
      images:
        - ghcr.io/pokt-network/pocket-operator:sha-6332dfc
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pocket-operator
  namespace: pocket-operator
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: controller-manager-metrics-service
