---
apiVersion: v1
kind: Namespace
metadata:
  name: protocol-common
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
  namespace: protocol-common
  labels:
    provisioned-by: "protocol"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
        provisioned-by: "protocol"
    spec:
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "512Mi"
          ports:
            - containerPort: 8547
          command: ["anvil"]
          args: ["-p", "8547", "-b", "5", "--host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: protocol-common
  labels:
    provisioned-by: "protocol"
spec:
  selector:
    app: anvil
  ports:
    - protocol: TCP
      name: rpc
      port: 8547
      targetPort: 8547
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: protocol-common
  name: nginx-evm-response
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-evm-response
  template:
    metadata:
      labels:
        app: nginx-evm-response
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-evm-response-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: protocol-common
  name: nginx-evm-response-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;

            location / {
                default_type application/json;
                return 200 '{"jsonrpc":"2.0","id":1,"result":"0xdeadbeef"}';
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: protocol-common
  name: nginx-evm-response
spec:
  selector:
    app: nginx-evm-response
  ports:
    - protocol: TCP
      name: rpc
      port: 8547
      targetPort: 80
