apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dmitry@grove.city
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dmitry@grove.city
    privateKeySecretRef:
      name: letsencrypt-production-dns
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-okdas
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poktroll-wildcard
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: poktroll-wildcard-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - pokt-network
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - poktroll.com
    - "*.poktroll.com"
    - "*.us-nj.poktroll.com"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-production-dns
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: poktroll-wildcard-tls
  namespace: cert-manager
spec:
  source:
    name: poktroll-wildcard-tls
  destination:
    namespaces:
      - devnet-.+
      - testnet-.+
      - .+-testnet
      - observability
      - path-e2e
      - protocol-common
