apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # https://argoproj.github.io/argo-cd/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          # kind: DaemonSet
          replicaCount: 2
          config:
            use-proxy-protocol: "false"
            # use-geoip: "true"
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 2
              memory: 3Gi
          # hostPort:
          #   enabled: true
          service:
            externalTrafficPolicy: Local
            # https://github.com/vultr/vultr-cloud-controller-manager/blob/master/docs/load-balancers.md
            annotations:
              service.beta.kubernetes.io/vultr-loadbalancer-algorithm: "least_connections"
              service.beta.kubernetes.io/vultr-loadbalancer-proxy-protocol: "false"
          # nodeSelector:
          #   vke.vultr.com/node-pool: static
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "app.kubernetes.io/name"
                        operator: In
                        values:
                        - ingress-nginx
                  topologyKey: "kubernetes.io/hostname"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/vultr-loadbalancer-algorithm: least_connections
#     service.beta.kubernetes.io/vultr-loadbalancer-proxy-protocol: "false"
#   finalizers:
#     - service.kubernetes.io/load-balancer-cleanup
#   name: ingress-nginx-controller-no-proxy
#   namespace: ingress-nginx
# spec:
#   allocateLoadBalancerNodePorts: true
#   externalTrafficPolicy: Local
#   selector:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/name: ingress-nginx
#   type: LoadBalancer
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
