apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-vm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.25.16
    helm:
      values: |
        fullnameOverride: vm
        argocdReleaseOverride: observability-vm
        vmsingle:
          enabled: false

        vmagent:
          spec:
            selectAllByDefault: true # all namespaces
            externalLabels:
              cluster: protocol-nj
              cloud_provider: vultr
              region: us-nj
              team: protocol

        vmalert:
          enabled: false

        victoria-metrics-operator:
          operator:
            disable_prometheus_converter: false
            prometheus_converter_add_argocd_ignore_annotations: true

        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - Replace=true
    # automated: # Enables automated sync
    #   prune: false # Enables pruning of resources not tracked anymore
    #   selfHeal: false # Enables self-healing of out-of-sync resources
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          image:
            tag: 2.9.9
          persistence:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: 100Gi
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - Replace=true
    # automated: # Enables automated sync
    #   prune: false # Enables pruning of resources not tracked anymore
    #   selfHeal: false # Enables self-healing of out-of-sync resources
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore

# Didn't realize VL still doesn't have Grafana integration
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: observability-vl
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://victoriametrics.github.io/helm-charts/
#     chart: victoria-logs-single
#     targetRevision: 0.3.4
#     helm:
#       values: |
#         server:
#           persistentVolume:
#             enabled: true
#             size: 30Gi
#         fluent-bit:
#           enabled: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: observability
#   syncPolicy:
#     syncOptions:
#       - Replace=true
#     automated: # Enables automated sync
#       prune: false # Enables pruning of resources not tracked anymore
#       selfHeal: false # Enables self-healing of out-of-sync resources
#   ignoreDifferences:
#     - group: cert-manager.io
#       kind: Certificate
#       jsonPointers:
#         - /spec/duration
#         - /spec/renewBefore
---

