# The purpose of resources mentioned here is to support PATH GitHub repo e2e suite
---
apiVersion: v1
kind: Namespace
metadata:
  name: path-e2e
---
# Anvil
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
  namespace: path-e2e
  labels:
    provisioned-by: "protocol"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
        provisioned-by: "protocol"
    spec:
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "512Mi"
          ports:
            - containerPort: 8547
          command: ["anvil"]
          args: ["-p", "8547", "-b", "5", "--host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: path-e2e
  labels:
    provisioned-by: "protocol"
spec:
  selector:
    app: anvil
  ports:
    - protocol: TCP
      name: rpc
      port: 8547
      targetPort: 8547
---
# Relayminer

# Relayminer key(s) are persisted in `path-relayminers` secret, which is created with the following command:
# kubectl create secret generic --context=vke-9c40c45d-3958-46fd-8b11-3f53643ba73e --namespace=path-e2e --from-file=./keyring-test/path-e2e-relayminer-1.info path-relayminers

# Staked manually with the following command:
# cat <<EOF >stake_config.yaml
# stake_amount: 1000000064upokt
# owner_address: pokt1ytsx06dfxrp7cgt7t95jkxuyu2m97563zqz5pn
# services:
# - service_id: anvil
#   endpoints:
#   - publicly_exposed_url: https://path-e2e-relayminer-1.us-nj.poktroll.com:443
#     rpc_type: json_rpc
# EOF
# pkd_beta_tx tx supplier stake-supplier --config=stake_config.yaml --from=path-e2e-relayminer-1 --yes

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: path-e2e-relayminer-1
  namespace: argocd
  labels:
    team: "protocol"
    purpose: "testnets"
    testnet: "testnet-beta"
    provisioned-by: "protocol"
spec:
  project: default
  destination:
    namespace: path-e2e
    server: https://kubernetes.default.svc
  source:
    path: charts/relayminer
    repoURL: https://github.com/pokt-network/helm-charts.git
    targetRevision: adopt-prod-image # TODO: change to versioned releases when the work on the helm chart is merged/done
    helm:
      values: |
        replicaCount: 1
        logs:
          level: debug # others are info
        chainId: pocket-beta
        keysSecretName: path-relayminers
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.3
            memory: 0.5Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        image:
          tag: sha-d573bfe # pr1027 # <- change this to the desired tag
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: path-e2e-relayminer-1.us-nj.poktroll.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: poktroll-wildcard-tls
              hosts:
                - path-e2e-relayminer-1.us-nj.poktroll.com
        grpcInsecure: true
        config:
          signing_key_name: path-e2e-relayminer-1
          default_signing_key_names: [path-e2e-relayminer-1]
          smt_store_path: /root/.poktroll/smt
          pocket_node:
            query_node_rpc_url: tcp://testnet-beta-fullnode2-poktrolld.testnet-beta:26657
            query_node_grpc_url: tcp://testnet-beta-fullnode2-poktrolld.testnet-beta:9090
            tx_node_rpc_url: tcp://testnet-beta-fullnode2-poktrolld.testnet-beta:26657
          suppliers:
            - service_id: anvil
              service_config:
                backend_url: http://anvil:8547/
                publicly_exposed_endpoints:
                  - path-e2e-relayminer-1.us-nj.poktroll.com
              listen_url: http://0.0.0.0:8545
