---
apiVersion: v1
kind: Namespace
metadata:
  name: testnet-offchain-actors
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-json-config
  namespace: testnet-offchain-actors
data:
  index.html: |
    {"success": true, "served_by": "static-nginx"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-nginx
  namespace: testnet-offchain-actors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-nginx
  template:
    metadata:
      labels:
        app: static-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-json-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: static-json-volume
          configMap:
            name: static-json-config
---
apiVersion: v1
kind: Service
metadata:
  name: static-nginx-service
  namespace: testnet-offchain-actors
spec:
  selector:
    app: static-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
