network:
  name: default-name
  type: devnet

image:
  tag: latest

# Version used for configs, keys, and persistence
# Defaults to image.tag if not specified
configVersion: ""

appgateservers:
  count: 1
gateways:
  count: 1
relayminers:
  count: 1
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.25
      memory: 512Mi
  services:
    anvil:
      backend_url: "http://anvil:8547/" # Default value
    anvilws:
      backend_url: "ws://anvil:8547/" # Default value

validator:
  resources:
    limits:
      memory: 1Gi
      cpu: 2
    requests:
      memory: 1Gi
      cpu: 0.5
  persistence:
    size: 10Gi # Default size for validator persistence

paths:
  image:
    tag: sha-1dc932f-rc # TODO: update to main
  count: 1
  replicas: 1
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.25
      memory: 512Mi
  full_node_config:
    rpc_url: ""
    grpc_config:
      host_port: ""
      insecure: true
    lazy_mode: true

charts:
  sequencer:
    branch: main
  appgate:
    branch: main
  relayminer:
    branch: main

customConfigMap:
  configsName: ""
  keysName: ""
  validator:
    enabled: false
    configs:
      app: ""
      client: ""
      config: ""
  fullnode:
    enabled: false
    configs:
      app: ""
      client: ""
      config: ""

# Additional arbitrary Kubernetes resources to be included with the release
additionalResources:
  []
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: extra-config
  #   data:
  #     key: value
  # - apiVersion: v1
  #   kind: Secret
  #   metadata:
  #     name: extra-secret
  #   stringData:
  #     key: value

fullnode:
  enabled: false # Disabled by default
  config:
    p2p:
      persistentPeers: ""
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 512Mi
      cpu: 0.5
  persistence:
    size: 10Gi # Default size for fullnode persistence
