network:
  name: default-name
  type: devnet

image:
  tag: latest

# Version used for configs, keys, and persistence
# Defaults to image.tag if not specified
configVersion: ""

appgateservers:
  count: 1
gateways:
  count: 1
relayminers:
  count: 1
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.25
      memory: 512Mi

validator:
  resources:
    limits:
      memory: 1Gi
      cpu: 2
    requests:
      memory: 1Gi
      cpu: 0.5
  persistence:
    size: 10Gi # Default size for validator persistence

paths:
  image:
    tag: main
  count: 1
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.25
      memory: 512Mi

charts:
  sequencer:
    branch: main
  appgate:
    branch: main
  relayminer:
    branch: main

customConfigMap:
  configsName: ""
  keysName: ""
  validator:
    enabled: false
    configs:
      app: ""
      client: ""
      config: ""
