network:
  name: default-name
  type: devnet

image:
  tag: latest

appgateservers:
  count: 1
gateways:
  count: 2
relayminers:
  count: 1

charts:
  sequencer:
    branch: main
  appgate:
    branch: main
  relayminer:
    branch: main

customConfigMap:
  configsName: ""
  keysName: ""

sequencer:
  persistence:
    cleanupBeforeEachStart: true
  resources:
    limits:
      cpu: 4
      memory: 6Gi
    requests:
      cpu: 0.5
      memory: 2Gi
  dataAvailability:
    provider: celestia
    authToken:
      secretName: celestia-secret
      secretKey: auth_token
    celestia:
      da_rpc_url: http://celestia-rollkit.protocol-common.svc.cluster.local:26658
      consensus_rpc_url: http://celestia-rollkit.protocol-common.svc.cluster.local:26657
