network:
  name: default-name
  type: devnet

image:
  tag: latest

appgateservers:
  count: 1
gateways:
  count: 1
relayminers:
  count: 1
paths:
  image:
    tag: main # TODO: add a way to change the tag for the path chart if this becomes necessary.
  count: 1

charts:
  sequencer:
    branch: main
  appgate:
    branch: main
  relayminer:
    branch: main

customConfigMap:
  configsName: ""
  keysName: ""
